/***** LOCALSTORAGE KEYS *****/
export const service_token_key = "service_token"
export const product_category_trees_key = "product_category_trees"
export const servcice_token_expires_in_key = "service_token_expires_in"
export const anonymous_token_key = "anonymous_token"
export const anonymous_token_expires_in_key = "anonymous_token_expires_in"
export const customer_token_key = "customer_token"
export const customer_token_expires_in_key = "customer_token_expires_in"
export const tenant_key = "tenant"
export const acess_token_key = "access_token"